Handle malformed payload for LinuxPackageOpened
endlessm/azafea pull request #158
Opened 2021-07-08 07:29 UTC by antoinehashbang

https://phabricator.endlessm.com/T32200

2021-07-08 12:19 UTC, dbnicholson requested changes
I left some minor comments, but this looks great. Thanks!

2021-07-08 12:19 UTC, dbnicholson commented on azafea/event_processors/endless/metrics/tests_v2/test_events.py
> +    assert lpo.argv == ['gnome-calendar.deb']
Could you add a second test here that creates the payload in the expected `as` format to ensure it gets through the parsing correctly?

2021-07-08 12:19 UTC, dbnicholson commented on azafea/event_processors/endless/metrics/v2/model/__init__.py
> +        if payload_type != self.__payload_type__ and payload_type != 's':
Could you add a comment explaining this?

2021-07-08 12:19 UTC, dbnicholson commented on azafea/event_processors/endless/metrics/v2/model/__init__.py
> +        if type(value) == str:
I don't think it makes any real difference, but I prefer `isinstance(value, str)`.

2021-07-09 12:13 UTC, dbnicholson approved these changes
This looks good to me. I'm going to merge this since it seems correct. @liZe when you get a chance could you take a look at this? I'm not familiar with the models here and want to make sure there's nothing wrong with the method overrides.

2021-07-09 12:13 UTC, merged

2021-07-09 12:17 UTC, liZe commented
Everything looks fine for me!